core/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path, include

from . import views

from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    
    path('contact/', views.contact, name='contact'),
    path('pricing/', views.pricing, name='pricing'),
    path('about/', views.about, name='about'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('todo/', views.todo, name='todo'),
    path('edit_todo/<int:pk>/', views.edit_todo, name='edit_todo'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
    path('signin/', auth_views.LoginView.as_view(template_name='core/sign-in.html', authentication_form=LoginForm), name='signin'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile', views.profile, name='profile'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('products', views.products, name='products'),
    path('dashboard/allinfo/', views.allinfo, name='allinfo'),
    path('dashboard/info/<int:pk>/', views.info, name='info'),
    path('dashboard/single_message/<int:pk>/', views.info, name='single_message'),
    path('info', views.info, name='info'),
]

item/urls.py
from django.urls import include, path
from . import views

app_name = 'items'

urlpatterns = [
    path('items/', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit', views.edit, name='edit'),
    path('<int:pk/add_comment/', views.add_comment, name='add_comment'),

]

nova/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from . import views


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Todo, Review, Messages

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('name', 'role', 'comment', 'image',)

        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'aria-label': 'form-control',
            }),

            'role': forms.TextInput(attrs={
                'class': 'form-control',
                'aria-label': 'form-control',
            }),

            'comment': forms.Textarea(attrs={
                'class': 'form-control',
                'aria-label': 'With textarea',
            }),

            'image': forms.FileInput(attrs={
                'class': 'form-control',
                'id': 'customFile',
                'label': 'Select an Image (optional)',
            }),
            
        }


class TodoForm(forms.ModelForm):
    STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('Completed', 'Completed'),
    ]

    content = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Add Todo...',
        'id': 'content',
        'aria-label': 'form-control',
        'autocomplete': 'off',
    }))

    tag = forms.ChoiceField(choices=STATUS_CHOICES, widget=forms.Select(attrs={
        'class': 'form-control',
        'id': 'tag',
        'aria-label': 'form-control',
    }))

    class Meta:
        model = Todo
        fields = ('content', 'tag')
       
        


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'Username',
    }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'id': 'Password',
    }))



class CustomUserCreationForm(UserCreationForm):
    # Adding custom attributes to the username field
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'registerUsername',
    }))

    # Adding email field with 'required' attribute
    email = forms.EmailField(max_length=30, required=True, widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'id': 'registerEmail',
    }))

    # Adding first_name field with 'required' attribute and max length
    first_name = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'registerName',
    }))

    # Adding last_name field with 'required' attribute and max length
    last_name = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'registerName',
    }))

    # Adding password fields with 'required' attribute and max length
    password1 = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'id': 'registerPassword',
    }))

    password2 = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'id': 'registerRepeatPassword',
    }))

    class Meta:
        model = User  # Assuming User is your custom User model
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')



class MessagesForm(forms.ModelForm):
    # Adding custom attributes to the username field
    name = forms.CharField(max_length=255, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'name',
        'placeholder': 'Your Name'

    }))

    # Adding email field with 'required' attribute
    email = forms.EmailField(max_length=255, required=True, widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'id': 'email',
        'placeholder': 'Your Email.'

    }))

    # Adding first_name field with 'required' attribute and max length
    subject = forms.CharField(max_length=255, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'subject',
        'placeholder': 'Subject.'

    }))

    # Adding last_name field with 'required' attribute and max length
    message = forms.CharField(max_length=500, required=True, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'id': 'message',
        'placeholder': 'Your message here...'
    }))

    class Meta:
        model = Messages  # Assuming User is your custom User model
        fields = ('name', 'email', 'subject', 'message')

core/views.py
from django.contrib.auth.decorators import login_required

from django.shortcuts import get_object_or_404, redirect, render

from item.models import Category, Item, User

from django.contrib import messages

from .models import *

from .forms import CustomUserCreationForm, LoginForm, TodoForm, ReviewForm, MessagesForm

from django.core.paginator import Paginator

from django.db.models import Q

from hitcount.views import HitCountDetailView

from django.urls import reverse

# Create your views here.

class ItemDetailView(HitCountDetailView):
    model = Item
    template_name = 'dat.html'
    count_hit = True

def index(request):
    items = Item.objects.all().order_by('?')
    service = ServiceInfo.objects.all()
    service_list = ServiceList.objects.all()

   
    qi = request.GET.get('qi', '')
    if qi:
        items = Item.objects.filter(name__icontains=qi) | Item.objects.filter(description__icontains=qi) | Item.objects.filter(created_by__username__icontains=qi)

    categories = Category.objects.all()
    num_users = User.objects.count()  

    paginate = Paginator(items, 3)
    page= request.GET.get('page')
    itemss = paginate.get_page(page)

    def get_ip(request):
        address = request.META.get('HTTP_X_FORWARDED_FOR')
        if address:
            ip = address.split(',')[-1].strip()
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    ip = get_ip(request)
    u = UserVisit(user=ip)
    print(ip)
    result = UserVisit.objects.filter(user__icontains=ip)
    if len(result) >= 1:
        # print("User exists")
        pass
    else:
        u.save()
        # print("User is Unique")
    count = UserVisit.objects.all().count()
    print("Total User is", count)



    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
        'itemss': itemss,
        'search_query': qi,
        'num_users': num_users,  
        'service': service,
        'service_list': service_list,
        'count': count,

    })

class PreventAuthMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        response = self.get_response(request)

        # Check if the user is authenticated
        if request.user.is_authenticated:
            # List of URLs to prevent authenticated users from accessing
            restricted_urls = [reverse('signup'), reverse('signin')]

            # Redirect authenticated users away from restricted URLs
            if request.path in restricted_urls:
                return redirect('index')  # Redirect to the home page or another appropriate URL

        return response

def contact(request):
    cons = ContactInfo.objects.all().order_by('id')


    if request.method == 'POST':
        form = MessagesForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.user = request.user  # Set the current user
            message.save()
            messages.success(request, 'Your message was sent successfully!')
            return redirect('/contact/')
        else:
            messages.error(request, 'Sending failed. Please correct the errors below.')

    else:
        form = MessagesForm()

    return render(request, 'core/contact.html', {
        'form': form,
        'cons': cons,
        'title': 'Contact Us'
    })

def pricing(request):
    return render(request, 'core/pricing.html')

def about(request):
    num_users = User.objects.count()  
    items = Item.objects.all().order_by('?')
    team = Team.objects.all().order_by('-id')
    about = AboutInfo.objects.all().order_by('id')



    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            review_instance = form.save(commit=False)
            review_instance.save()
            return redirect('core:about')  
        else:
            pass
    else:
        form = ReviewForm()

    reviews = Review.objects.all().order_by('?')  # Fetch all reviews

    paginate = Paginator(reviews, 5)
    page= request.GET.get('page')
    rev = paginate.get_page(page)

    return render(request, 'core/about.html', {
        # 'reviews': reviews,
        'rev': rev, 
        'form': form,
        'num_users': num_users,  
        'items': items,
        'team': team,
        'about': about,
        

        })

def todo(request):
    # Handling POST request (form submission)
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            todo_instance = form.save(commit=False)
            if request.user.is_authenticated:
                todo_instance.user = request.user  # Set the user for the todo
                todo_instance.save()
                return redirect('core:todo')  # Redirect to the todo view after saving
            else:
                # Redirect to login if the user is not authenticated
                return redirect('signin')
        else:
            # Handle form errors (you might want to pass the form back to the template)
            pass
    else:
        form = TodoForm()

    # Fetching todos for the current user
    todos = Todo.objects.filter(user=request.user) if request.user.is_authenticated else []

    # Render the template with the form and the list of todos
    return render(request, 'core/TODO.html', {
        'form': form, 
        'todos': todos,
        'title': 'Todos',

        })


def edit_todo(request, pk):
    todo = get_object_or_404(Todo, pk=pk, user=request.user)

    if request.method == 'POST':
        form = TodoForm(request.POST, instance=todo)
        if form.is_valid():
            form.save()
            return redirect('core:todo')
    else:
        form = TodoForm(instance=todo)

    return render(request, 'core/TODO.html', {
        'form': form,
        'title': 'Edit Todo',
    })


def delete(request, pk):
    todo = get_object_or_404(Todo, pk=pk, user=request.user)

    if request.method == 'POST':
        todo.delete()
        return redirect('core:todo')

    return render(request, 'core/TODO.html', {
        'todo': todo,
        'title': 'Confirm Delete',
    })




def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Registration successful!')
            return redirect('/signin/')
        else:
            # If form is not valid, add an error message
            messages.error(request, 'Registration failed. Please correct the errors below.')
            form.non_field_errors()
            # Redirect to a specific ID on the members page
            return redirect('/signup/')
    else:
        form = CustomUserCreationForm()

    return render(request, 'core/sign-up.html', {'form': form})


def terms(request):
    terms = Terms.objects.all()

    return render(request, 'core/terms.html', {
        'terms': terms,
        'title': 'Terms and Conditions',
    })

def privacy(request):
    privacy = Privacy.objects.all()

    return render(request, 'core/privacy.html', {
        'privacy': privacy,
        'title': 'Privacy Policy',
    })

core/templates/core/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    <title>Fresh | {% block title %} {% endblock %}</title>
    <meta content="" name="description" />
    <meta content="" name="keywords" />

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon" />
    <link
      href="{% static 'img/apple-touch-icon.png' %}"
      rel="apple-touch-icon"
    />

    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->

    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet" />
    <link
      href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'vendor/fontawesome-free/css/all.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'vendor/glightbox/css/glightbox.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'vendor/swiper/swiper-bundle.min.css' %}"
      rel="stylesheet"
    />

    <!-- MDB -->
    <link rel="stylesheet" href="{% static 'vendor/md/css/mdb.min.css' %}" />

    <!-- Template Main CSS File -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

    
  </head>

  <body>
    <!-- ======= Header ======= -->

    <header
      id="header"
      class="header d-flex align-items-center fixed-top w-75 m-auto bg-light mt-4 bg-opacity-75 p-1"
    >
      <div class="container p-0 w-100">
        <nav class="navbar">
          <div class="logg">
            <div class="logg1">
              <a
                href="{% url 'core:index' %}"
                class="logo d-flex align-items-center"
              >
                <!-- Uncomment the line below if you also wish to use an image logo -->
                <!-- <img src="assets/img/logo.png" alt=""> -->
                <h1>BRAND NOVA</h1>
              </a>
            </div>

            <div class="logg2">
              <span class="n-t1"><i class="bi bi-list"></i></span>
              <span class="n-t2"><i class="bi bi-x"></i></span>
            </div>
          </div>
          <ul class="n-list justify-content-end px-3">
            <li><a href="{% url 'core:index' %}" class="active">Home</a></li>
            <li><a href="{% url 'core:about' %}">About</a></li>
            <li><a href="{% url 'core:contact' %}">Contact</a></li>
            <li><a href="{% url 'core:pricing' %}">Pricing</a></li>
            <li class="dropdown">
              <a href="#!"
                ><span>Drop Down</span>
                <i class="bi bi-chevron-down dropdown-indicator"></i
              ></a>
              <ul style="width: auto">

                <li><a href="
                  {% if request.user.is_authenticated %}
                    {% url 'core:todo' %}
                  {% else %}
                    {% url 'core:signin' %}
                  {% endif %}
                  ">Todo List</a></li>
                <li><a href="#">Drop Down 2</a></li>
                <li><a href="{% url 'core:terms' %}">Terms and Conditions</a></li>
                <li><a href="{% url 'core:privacy' %}">Privacy and Security</a></li>
              </ul>
            </li>
            {% if request.user.is_authenticated %}
            <li class="p-0">
              <a
                class="bg-success get-a-quote"
                href="{% url 'dashboard:index' %}"
                >Dashboard</a
              >
            </li>
            {% else %}
            <li class="p-0">
              <a class="get-a-quote" href="{% url 'core:signup' %}"
                >Register With Us</a
              >
            </li>
            <li class="p-0">
              <a class="bg-success get-a-quote" href="{% url 'core:signin' %}"
                >Login</a
              >
            </li>
            {% endif %}
          </ul>
        </nav>
        <!-- .navbar -->
      </div>
      <style>
        
        .bonus_area
        {
            position: fixed;
        top: 50%;
        right: 0;
        width: 180px;
        border-radius: 5px 0 0 5px;
        z-index: 99999998;
        -webkit-transform: translateY(-50%) translateX(100%);
        -ms-transform: translateY(-50%) translateX(100%);
        transform: translateY(-50%) translateX(100%);
        -webkit-transition: all 1s ease;
        -o-transition: all 1s ease;
        transition: all 1s ease;
        }
        .bonus_area.show
        {
            -webkit-transform: translateY(-50%) translateX(0%);
        -ms-transform: translateY(-50%) translateX(0%);
        transform: translateY(-50%) translateX(0%);
        -webkit-box-shadow: 0 0 50px rgba(0, 0, 0, 0.3);
        box-shadow: 0 0 50px rgba(0, 0, 0, 0.3);
        }
        .bonus_area .inner_area
        {
            background: -webkit-gradient(linear, left top, left bottom, from(#202b47), to(#5846f9));
        background: -webkit-linear-gradient(top, #202b47 0%, #5846f9 100%);
        background: -o-linear-gradient(top, #202b47 0%, #5846f9 100%);
        background: linear-gradient(to bottom, #5846f9 0%, #202b47 100%);
        border-radius: 5px 0 0 0;
        padding: 18px 0 23px;
        position: relative;
        text-align: center;
        }
        .bonus_area .inner_area .icon
        {
            display: block;
        padding-left: 33px;
        margin-bottom: 15px;
        text-align: left;
        }
        .inner_area .close-btn 
        {
            position: absolute;

        height: 20px;
        background: none;
        outline: none;
        border: none;
        z-index: 30;
        top: 28px;
        width: 10px;
        height: 15px;
        right: 20px;
        }
        hr{
          color: wheat;
        }

      </style>
    </header>
    <!-- End Header -->
    <!-- End Header -->
    <!-- Start Page  -->

    {% block content %} {% endblock %}

    <div class="bonus_area rounded-lg">
      <div class="inner_area">
          <button class="global-close-btn close-btn" data-dismiss="modal">
            <i class="bi bi-x-lg text-light" style="font-size: 10px;"></i>
          </button>
          <div class="icon">
            <i class="bi bi-code-slash text-light" style="font-size: 30px;"></i>
          </div>
          <h4 class="mt-5 text-white"><strong>JOIN US</strong></h4>
          <p class="subtitle text-white">And get access to free coding tutorials and many more related content.</p>
          <hr>
          <a href="https://justmarkettrades.com/register" class="get-btn text-light" style="text-decoration: none;">Register Now</a>
      </div>
    </div>

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-5 col-md-12 footer-info">
            <a
              href="{% url 'core:index' %}"
              class="logo d-flex align-items-center"
            >
              <span>BRAND NOVA</span>
            </a>
            <p class="text-center">
              Welcome to Brand Nova, your ultimate destination for all things web. We specialize in delivering innovative web design templates, engaging tutorials, and a dynamic online community platform.
            </p>
          </div>
        </div>
      </div>

      <div class="container mt-4">
        <div class="copyright">
          &copy; Copyright <strong><span>BRAND NOVA</span></strong
          >. All Rights Reserved
        </div>
      </div>
    </footer>
    <!-- End Footer -->
    <!-- End Footer -->

    <a
      href="#"
      class="scroll-top d-flex align-items-center justify-content-center"
      ><i class="bi bi-arrow-up-short"></i
    ></a>

    <div id="preloader"></div>

    <!-- End Page  -->

    <!-- Vendor JS Files -->
    <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'vendor/aos/aos.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>

    <!-- MDB -->
    <script
      type="text/javascript"
      src="{% static 'vendor/md/js/mdb.min.js' %}"
    ></script>

    <!-- Template Main JS File -->
    <script src="{% static 'js/main.js' %}"></script>

    <!-- Chart Js -->
    <script src="{% static 'js/chart.js' %}"></script>

    <!-- J Queery -->
    <script src="{% static 'js\jquery-3.7.1.min.js' %}"></script>

    <script>

      $(document).ready(function () {
        
        //Navbar

        $(".n-t1").click(function () {
          $(this).hide();
          $(".n-t2").show();
          $(".navbar").css("height", "500px");
        });

        $(".n-t2").click(function () {
          $(this).hide();
          $(".n-t1").show();
          $(".navbar").css("height", "60px");
        });

        $(".dropdown").click(function () {
          $(".dropdown ul").toggle();
        });

        $(".flip").click(function(){
          $(".panel").slideToggle("slow");
        });


        //side notification

        setTimeout(function() {
          $(".bonus_area").addClass("show");
        }, 5000);
  
        $(".close-btn").click(function() {
          $(".bonus_area").removeClass("show");
        });




      });
    </script>
  </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="hero d-flex align-items-center">
    <div class="container">
      <div class="row gy-4 d-flex justify-content-between">
        <div class="col-lg-6 order-2 order-lg-1 d-flex flex-column justify-content-center">
          <h2 class="text-center" data-aos="fade-up">Welcome To Brand Nova.</h2>
          <h4 class="text-center" data-aos="fade-up">All Things Web.</h4>
          <p data-aos="fade-up" data-aos-delay="100">Welcome to Brand Nova, the hub for web creativity and learning. Discover our range of web design templates, insightful tutorials, and an engaging community platform. Catering to both novices and experts, Brand Nova is your go-to source for web design inspiration and skill enhancement.</p>

          <form action="{% url 'core:index' %}" method="GET" class="form-search d-flex align-items-stretch mb-3" data-aos="fade-up" data-aos-delay="200">
            {% csrf_token %}
            <input type="text" name="qi" class="form-control" placeholder="Searching for Something?" value="{{ search_query }}">
            <button type="submit" class="btn btn-primary">Search</button>
          </form>

          <div class="row gy-4" data-aos="fade-up" data-aos-delay="400">

            <div class="col-lg-3 col-6">
              <div class="stats-item text-center w-100 h-100">
                <span data-purecounter-start="0" data-purecounter-end=" {{ num_users }} " data-purecounter-duration="1" class="purecounter"></span>
                <p>Clients</p>
              </div>
            </div><!-- End Stats Item -->

            <div class="col-lg-3 col-6">
              <div class="stats-item text-center w-100 h-100">
                <span data-purecounter-start="0" data-purecounter-end="{{ items|length }}" data-purecounter-duration="1" class="purecounter"></span>
                <p>Posts</p>
              </div>
            </div><!-- End Stats Item -->

            <div class="col-lg-3 col-6">
              <div class="stats-item text-center w-100 h-100">
                <span data-purecounter-start="0" data-purecounter-end="1453" data-purecounter-duration="1" class="purecounter"></span>
                <p>Support</p>
              </div>
            </div><!-- End Stats Item -->

            <div class="col-lg-3 col-6">
              <div class="stats-item text-center w-100 h-100">
                <span data-purecounter-start="0" data-purecounter-end="{{ count }}" data-purecounter-duration="1" class="purecounter"></span>
                <p>Visits</p>
              </div>
            </div><!-- End Stats Item -->

          </div>
        </div>

        <div class="col-lg-5 order-1 order-lg-2 hero-img" data-aos="zoom-out">
          <img src="#" class="img-fluid mb-3 mb-lg-0" alt="">
        </div>

      </div>
    </div>
  </section><!-- End Hero Section -->

  <main id="main" class="main">

    <!-- ======= Featured Services Section ======= -->
    <section id="featured-services" class="featured-services">
      <div class="container">

        <div class="section-header">
          <span>Daily Quotes</span>
          <h2>Daily Quotes</h2>

        </div>

        <div class="row gy-4">
          
          {% for item in itemss %}

          <div class="col-lg-4 col-md-6 service-item d-flex" data-aos="fade-up">
            <div class="icon flex-shrink-0">
              <img src="{{ item.image.url }}" class="testimonial-img rounded" alt="" style="height: 60px; width: 60px; border: 1px solid #001973; box-shadow: 0px 0px 10px #001973;">
            </div>
            <div>
              <h4 class="title">{{ item.name }}</h4>
              <p class="description">{{ item.description }}</p>
              <i> <b>Posted By: </b> {{ item.created_by.username }}</i>
              <a href="{% url 'items:detail' item.id %}" class="readmore stretched-link"><span>Posted At: </span><i>{{ item.created_at }}</i></a>
            </div>
          </div>

          {% endfor %}
          <!-- End Service Item -->


        </div>
        <a href="{% url 'items:items' %}" class="btn btn-primary">
          See More <span class="badge text-bg-secondary"> {{ items|length }}</span>
        </a>
      </div>
    </section>

     <!-- ======= Call To Action Section ======= -->
     <section id="call-to-action" class="call-to-action mb-3">
      <div class="container" data-aos="zoom-out">

        <div class="row justify-content-center">
          <div class="col-lg-8 text-center">
            <h3>Hire Us</h3>
            <p> Need a visually stunning website to promote your business or create an online presence or are you simply interested in our content? You can reach out to us and get quick response from any of our professionals to discuss your requirements.</p>
            <a class="cta-btn" href="{% url 'core:contact' %}">Contct Us</a>
          </div>
        </div>

      </div>
    </section><!-- End Call To Action Section -->

    {% if service %}
       <!-- ======= Features Section ======= -->
      <section id="features" class="features">
        <div class="container">

          <div class="section-header">
            <span>Our Services</span>
            <h2>Our Services</h2>
          </div>

          {% for service in service %} 
        
            {% if service.list.exists and not service.content %}

              <div class="row gy-4 align-items-center features-item rounded" data-aos="fade-up" style="border-radius: 15px;box-shadow: 0 1px 3px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
              ">
                <div class="col-md-5">
                  <img src="
                  {% if service.image %}
                    {{ service.image.url }}
                  {% else %}
                    #
                  {% endif %}
                  " class="img-fluid rounded mb-3" alt="{{ service.name }}">
                </div>
                <div class="col-md-7 p-3">
                  <h3>{{ service.name }}</h3>
                  <p class="fst-italic">
                    {{ service.description }} 
                  </p>
                  <ul>
                    {% for service_list in service.list.all %}
                      <li><i class="bi bi-check"></i> {{ service_list.name }}</li> 
                    {% endfor %}
                  </ul>
                </div>
              </div>

            {% elif service.content %}

              <div class="row gy-4 align-items-center features-item rounded" data-aos="fade-up" style="border-radius: 15px;box-shadow: 0 1px 3px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
              ">
                <div class="col-md-5 order-1 order-md-2">
                  <img src="
                  {% if service.image %}
                    {{ service.image.url }}
                  {% else %}
                    #
                  {% endif %}
                  " class="img-fluid rounded" alt="{{ service.name }}">
                </div>
                <div class=" p-3 col-md-7 order-2 order-md-1">
                  <h3>{{ service.name }}</h3>
                  <p class="fst-italic">
                    {{ service.description }}
                  </p>
                  <p>
                    {{ service.content }}
                  </p>
                </div>
              </div>
            
            {% endif %}
          
          {% endfor %}
      
        </div>
      </section><!-- End Features Section -->

    {% else %}

    {% endif %}
    

     

{% endblock %}