core/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path, include

from . import views

from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    
    path('contact/', views.contact, name='contact'),
    path('pricing/', views.pricing, name='pricing'),
    path('about/', views.about, name='about'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('todo/', views.todo, name='todo'),
    path('edit_todo/<int:pk>/', views.edit_todo, name='edit_todo'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
    path('signin/', auth_views.LoginView.as_view(template_name='core/sign-in.html', authentication_form=LoginForm), name='signin'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

item/urls.py
from django.urls import include, path
from . import views

app_name = 'items'

urlpatterns = [
    path('items/', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit', views.edit, name='edit'),
    path('<int:pk/add_comment/', views.add_comment, name='add_comment'),

]

nova/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from . import views


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    
class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    content = RichTextUploadingField(blank=True, null=True) 
    # content = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    file = models.FileField(upload_to='item_files', blank=True)
    video = models.FileField(upload_to='item_videos', blank=True)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Comment(models.Model):
    item = models.ForeignKey(Item, related_name='comments', on_delete=models.CASCADE)
    name =  models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    body = models.TextField()
    posted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.item.name, self.name)
    

item/forms.py
from django import forms

from .models import *

from django.forms import ModelForm

from django.forms import BaseFormSet, BaseModelFormSet

# forms.py

# ...


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'content', 'image',)

        widgets = {
            'category': forms.Select(attrs={
                'class': 'form-select',
                'aria-label': '.form-select',
            }),

            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'aria-label': '.form-control',
            }),

            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'aria-label': 'With textarea',
            }),

            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'aria-label': 'With textarea',
            }),

            'image': forms.FileInput(attrs={
                'class': 'form-control',
                'id': 'customFile',
            }),
            
        }


# class NewItemForm(forms.ModelForm):
#     class Meta:
#         model = Item
#         fields = ('name', 'description', 'content', 'image', 'category')

#         widgets = {
#             'name': forms.TextInput(attrs={
#                 'class': 'form-control',
#                 'aria-label': '.form-control',
#             }),
#             'description': forms.Textarea(attrs={
#                 'class': 'form-control',
#                 'aria-label': 'With textarea',
#             }),
#             'content': forms.Textarea(attrs={
#                 'class': 'form-control',
#                 'aria-label': 'With textarea',
#             }),
#             'image': forms.FileInput(attrs={
#                 'class': 'form-control',
#                 'id': 'customFile',
#             }),
#         }

#     def __init__(self, user, *args, **kwargs):
#         super(NewItemForm, self).__init__(*args, **kwargs)

#         # Restrict users to a single category
#         if not user.is_superuser:
#             allowed_category = Category.objects.get(name='Quotes')
#             self.fields['category'].queryset = Category.objects.filter(pk=allowed_category.pk)
#             self.fields['category'].initial = allowed_category
#             self.fields['category'].widget.attrs['disabled'] = 'disabled'
#         else:
#             self.fields['category'].widget = forms.Select(attrs={
#                 'class': 'form-select',
#                 'aria-label': '.form-select',
#             })




class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'content', 'image',)

        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'aria-label': '.form-control',
            }),

            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'aria-label': 'With textarea',
            }),

            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'aria-label': 'With textarea',
            }),

            'image': forms.FileInput(attrs={
                'class': 'form-control',
                'id': 'customFile',
            }),
            
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        labels = {
            'body': 'Comment',
        }
        widgets = {
            'body': forms.TextInput(attrs={
                'class': 'form-control',
                'aria-label': 'form-control',
                'placeholder': 'Leave a Comment...',
                'autocomplete': 'off',
                
            }),
        }

        

item/views.py
from django.contrib.auth.decorators import login_required

from django.db.models import Count

from django.shortcuts import redirect, render, get_object_or_404

from .forms import EditItemForm, NewItemForm, CommentForm

from .models import Category, Item, Comment

from dashboard.models import Profile

# Create your views here.

def items(request):
    category_id = request.GET.get('category', None)
    categories = Category.objects.annotate(item_count=Count('items'))  
    

    if category_id:
        filtered_items = Item.objects.filter(category_id=category_id)
    else:
        filtered_items = Item.objects.all()

    return render(request, 'item/items.html', {
        'categories': categories,
        'items': filtered_items,
        'category_id': int(category_id) if category_id else None,
        'title': 'All Uploads',

    })

def item_detail(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    comments = Comment.objects.filter(post=item)
    return render(request, 'details.html', {'post': item, 'comments': comments})

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category).exclude(pk=pk)
    badge = Profile.badge

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            if request.user.is_authenticated:
                comment.name = request.user  # Set the user from the request
                comment.item = item
                comment.save()
                return redirect('items:detail', pk=item.id)
            else:
                pass
    else:
        form = CommentForm()

    return render(request, 'item/detail.html', {
        'badge': badge,
        'item': item,
        'related_items': related_items,
        'form': form,
    })

@login_required(login_url='signin')  
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('items:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New Post',
        })

@login_required
def edit(request,pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()
            return redirect('items:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit Post',
        })

@login_required(login_url='signin')
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()
    return redirect('dashboard:index')

def add_comment(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            if request.user.is_authenticated:
                comment.name = request.user  # Set the user from the request
                comment.item = item
                comment.save()
                return redirect('items:detail', pk=item.id)
            else:
                pass
    else:
        form = CommentForm()

    return render(request, 'item/detail.html', {'form': form, 'item': item})

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% load hitcount_tags %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <div class="page-header d-flex align-items-center" style="background-image: url('/static/img/page-header.jpg');">
        <div class="container position-relative">
          <div class="row d-flex justify-content-center">
            <div class="col-lg-6 text-center">
              <h2>Details</h2>
            </div>
          </div>
        </div>
      </div>
      <nav>
        <div class="container">
          <ol>
            <li><a href="{% url 'core:index' %}">Home</a></li>
            <li>Details</li>
          </ol>
        </div>
      </nav>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Service Details Section ======= -->
    <section id="service-details" class="service-details">
      <div class="container" data-aos="fade-up">

        <div class="row gy-4">

          <div class="col-lg-4">
            <h4>View Similar Uploads</h4>

            <div class="services-list" style="height:300px; width:300px; overflow-y:scroll;">
              {% for item in related_items %}
              <a href="{% url 'items:detail' item.id %}">{{ item.name }}</a>
              {% endfor %}
            </div>

            <p class="text-center">
             <div class="card p-3">
              Here is a list of other uploads under similar category. You can browse the list to see other interesting uploads.
             </div>

            </p>
          </div>

          

          <div class="col-lg-8">
            <img src="
              {% if item.image %}
                {{ item.image.url }}
              {% else %}
                #
              {% endif %}
              " alt="" class="img-fluid services-img rounded" style=" width:60%;">

            <h3>{{ item.name }}</h3>
            <p>
              -- <i>{{ item.description }}</i> --
            </p>
            {% if item.content %}
            <p>
              {{ item.content|safe }}
            </p>
            {% else %}
            <p>
              <div class="text-center container">
                <I class="p-2 rounded bg-danger bg-opacity-25 shadow ">
                  <b>There's no further content on this upload, leave a comment to share your opinion on the post.</b>
                </i>
              </div>
            </p>
            {% endif %}
          </div>

          {% if item.video %}
            <video class="embed-responsive embed-responsive-16by9" controls="controls">
              <source src="{{ item.video.url }}" type="video/mp4">
            </video>

          {% endif %}

          <div class="d-flex" style="flex-direction: row;">
            <ul>
              {% if request.user == item.created_by %}
              <li>
                <div id="liveAlertPlaceholder" class=" d-flex"></div>
  
              </li>
              <li><i class="bi bi-check-circle"></i>
                <span>Posted By: </span ><i> You</i>
  
                <button type="button" class="btn btn-danger me-3" id="liveAlertBtn">Delete</button>
  
                <a href="{% url 'items:edit' item.id %}" class="btn btn-success">Edit</a>
              </li>
              {% else %}
              <li><i class="bi bi-check-circle"></i>
                <span>Posted By: </span> <i> {{ item.created_by }}</i>
              </li>
              
              {% endif %}
              <li><i class="bi bi-clock"></i>
                <span>Posted At: </span> <i> {{ item.created_at }}</i>
              </li>
              <li><i class="bi bi-eye"></i>
                <span>Views: </span><div> <i>{% get_hit_count for item %}</i> Views</div> 
              </li>
            </ul>
              {% if user.is_authenticated %}
                {% if item.file %}
                <div class="card p-3 ms-auto">
                  <h3 class="text-dark">Downloadable File</h3>
                  <div class="card-body text-center" style="font-size: larger;">
                    <a href="{% if item.file %} {{ item.file.url }} {% else %} # {% endif %}" download class="btn-visit align-self-start"><i class="btn text-primary bi bi-download"></i></a>
                  </div>
                </div>
                {% endif %}
              {% else %}
                <a href="{% url 'core:signin' %}" class="btn-visit align-self-start">Signin to Download</a>   
              {% endif %}
          </div>
          
        </div>

        <h2>Comments</h2>

        {% if item.comments.all %}
            {% for comment in item.comments.all %}
                {% if request.user == comment.name %}
                  <div class="container my-3">
                    <div class="card">
                      <div class="card-header bg-warning bg-opacity-50" style="display: flex; justify-content: end;">
                        <b>{{ comment.name }} 
                          {% if badge %}
                            {{ profile.badge|safe }}
                          {% endif %}
                        </b>
                      </div>
                      <div class="card-body bg-secondary" style="display: flex; justify-content: end;">
                        {{ comment.body }}
                      </div>
                    </div>
                    <small class="me-5 " style="display: flex; justify-content: end;"><i>{{ comment.posted_at }}</i></small>
                  </div>
                {% else %}
                  <div class="container my-3">
                    <div class="card">
                      <div class="card-header bg-primary bg-opacity-50">
                        <b>{{ comment.name }} 
                          {% if profile.badge %}
                            {{ profile.badge|safe }}
                          {% endif %}
                        </b>
                      </div>
                      <div class="card-body bg-secondary">
                        {{ comment.body }}
                      </div>
                    </div>
                    <small class="ms-5"><i>{{ comment.posted_at }}</i></small>
                  </div>
                {% endif %}
            {% endfor %}
        {% else %}
            <p class="my-3">
              No Comments...
            </p>
        {% endif %}

        <div class="container">
          <form action="." method="POST" class="form-group">
            {% csrf_token %}
            {% if request.user.is_authenticated %}
              <div class="form-outline my-4">
                {{ form.non_field_errors }}
                {{ form.body.errors }}
                {{ form.body }}
              </div>
              <p style=" display: flex; width: 100%; justify-content: end;">
                <button type="submit" class="btn btn-warning">Comment</button>
              </p>
            {% else %}
              <p style="display: flex; width: 100%; justify-content: end;">
                <a href="{% url 'core:signin' %}" class="btn btn-warning">Sign in to Comment</a>
              </p>
            {% endif %}
          </form>
        </div>



    <script>
      const alertPlaceholder = document.getElementById('liveAlertPlaceholder')
      const appendAlert = (message, type) => {
        const wrapper = document.createElement('div')
        wrapper.innerHTML = [
          `<div class="alert alert-${type} alert-dismissible" role="alert">`,
          `   <div>${message}</div>`,
          '   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>',
          '</div>'
        ].join('')

        alertPlaceholder.append(wrapper)
      }

      const alertTrigger = document.getElementById('liveAlertBtn')
      if (alertTrigger) {
        alertTrigger.addEventListener('click', () => {
          appendAlert('<h5>Are you sure you want to delete this post?</h5> <a href="{% url 'items:delete' item.id %}" class="btn btn-danger">Delete</a>', 'danger')
        })
      }
    </script>

  </main><!-- End #main -->

  {% endblock %}

item/templates/item/form.html
{% extends 'dashboard/base.html' %}

{% block title %}{{title}}{% endblock %}


{% block content %}
    <div class="section-header">
        <span>{{title}}</span>
        <h2>{{title}}</h2>
    </div>
    

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="">
            {{ form.media }}
            {{ form.as_p }}
        </div>
        {% if form.errors or form.non_field_errors %}
            <div class="alert alert-danger alert-dismissible fade show p-2" role="alert">
            <p class="text-center" style="list-style:none;">
                {% for field in form %}
                    <p>
                      {{ field.errors }}
                    </p>
                {% endfor %}
                {{ form.non_field_errors }}
            </p>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}

        <div class="d-flex justify-content-end pt-1 mb-4">
        <button class="btn btn-primary btn-rounded" type="submit" style="background-color: #92aad0;">Submit</button>
        </div>
    </form>

{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}
    All Quotes
{% endblock %}

{% block content %}


    <section id="featured-services" class="featured-services">
        <div class="container">

            <div class="section-header">
                <span>{{ title }}</span>
                <h2>{{ title }}</h2>

            </div>

            <ul class="list-group m-5">
                <li class="list-group-item d-flex justify-content-center align-items-center text-center">
                    <span class="rounded"><h3>Categories</h3></span>
                </li>
                
                {% for category in categories %}
                <a href="{% url 'items:items' %}?query={{ query }}&category={{ category.id }}">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        See More in {{ category.name }}
                    <span class="badge bg-primary rounded-pill">
                        {% if category.item_count > 99 %}
                            99+
                        {% else %}
                            {{ category.item_count }}
                        {% endif %}
                    </span>
                    </li>
                </a>
                {% endfor %}
            </ul>

            <div class="row gy-4">
            
                {% if items %}
                    {% for item in items %}

                        <div class="col-lg-4 col-md-6 service-item d-flex" data-aos="fade-up">
                        <div class="icon flex-shrink-0">
                            <img src="{{ item.image.url }}" class="testimonial-img rounded" alt="" style="height: 60px; width: 60px; border: 1px solid #001973; box-shadow: 0px 0px 10px #001973;">
                        </div>
                        <div>
                            <h4 class="title">{{ item.name }}</h4>
                            <p class="description">{{ item.description }}</p>
                            <i> <b>Posted By: </b> {{ item.created_by.username }}</i>
                            <a href="{% url 'items:detail' item.id %}" class="readmore stretched-link"><span>Posted At: </span><i>{{ item.created_at }}</i></a>
                        </div>
                        </div>

                    {% endfor %}
                {% else %}
                    <p>No items in this category.</p>
                {% endif %}
                    <!-- End Service Item -->


            </div>
        </div>
    </section>



{% endblock %}