core/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path, include

from . import views

from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    
    path('contact/', views.contact, name='contact'),
    path('pricing/', views.pricing, name='pricing'),
    path('about/', views.about, name='about'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('todo/', views.todo, name='todo'),
    path('edit_todo/<int:pk>/', views.edit_todo, name='edit_todo'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
    path('signin/', auth_views.LoginView.as_view(template_name='core/sign-in.html', authentication_form=LoginForm), name='signin'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile', views.profile, name='profile'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('products', views.products, name='products'),
    path('dashboard/allinfo/', views.allinfo, name='allinfo'),
    path('dashboard/info/<int:pk>/', views.info, name='info'),
    path('dashboard/single_message/<int:pk>/', views.info, name='single_message'),
    path('info', views.info, name='info'),
]

item/urls.py
from django.urls import include, path
from . import views

app_name = 'items'

urlpatterns = [
    path('items/', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit', views.edit, name='edit'),
    path('<int:pk/add_comment/', views.add_comment, name='add_comment'),

]

nova/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from . import views


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.utils import timezone
from django.db import models

from django.contrib.auth.models import User

from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    badge = models.CharField(max_length=255, blank=True)
    bio = models.CharField( max_length=255, null=True)
    country = models.CharField(max_length=255, null=True)
    phone = models.CharField(max_length=255, null=True)
    address = models.CharField(max_length=255, null=True)
    job = models.CharField(max_length=255, null=True)
    image = models.ImageField(upload_to='user_images', blank=True, null=True)


    def __str__(self):
        return str(self.user)

class Events(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=255, blank=True)
    image = models.ImageField(upload_to='event_images', blank=True, null=True)
    duration = models.CharField(null=True, blank=True, max_length=255)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ('title',)
        verbose_name_plural = 'Events'

    def __str__(self):
        return str(self.title)


class Info(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField(blank=True)
    status = models.BooleanField(default=False, help_text="Read")
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title

dashboard/forms.py
from django import forms
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile



class ProfileForm(forms.ModelForm):
    bio = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'about',
    }))

    country = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={  # Changed to CharField
        'class': 'form-control',
        'id': 'Country',
    }))

    phone = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'Phone',
    }))

    address = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'address',
    }))

    job = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'job',
    }))

    image = forms.ImageField(required=False, widget=forms.FileInput(attrs={  # Set required=False if the image is optional
        'class': 'form-control',
        'id': 'customFile',
    }))

    class Meta:
        model = Profile
        fields = ('bio', 'country', 'phone', 'address', 'job', 'image',)

    
class UserForm(forms.ModelForm):
    # Adding custom attributes to the username field
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'registerUsername',
    }))

    # Adding email field with 'required' attribute
    email = forms.EmailField(max_length=30, required=True, widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'id': 'registerEmail',
    }))

    # Adding first_name field with 'required' attribute and max length
    first_name = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'registerName',
    }))

    # Adding last_name field with 'required' attribute and max length
    last_name = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'registerName',
    }))

    class Meta:
        model = User  # Assuming User is your custom User model
        fields = ('username', 'email', 'first_name', 'last_name')

dashboard/views.py
from django.contrib.auth.decorators import login_required

from django.shortcuts import get_object_or_404, redirect, render

# from django.db.models.functions import TruncMonth

# from django.db.models import Count

from django.urls import reverse_lazy

from item.models import Item, Comment

from .models import *

from .forms import *

from core.models import Messages

from django.contrib.auth.forms import UserChangeForm

from django.core.paginator import Paginator

# Create your views here.




@login_required(login_url='signin')
def index(request):
    items = Item.objects.filter(created_by=request.user)
    comment = Comment.objects.filter(name=request.user)
    mess = Messages.objects.filter(user=request.user)
    events = Events.objects.all()
    info = Info.objects.filter(user=request.user, status=False).order_by('-id')

    return render(request, 'dashboard/index.html', {
        'items': items,
        'comment': comment,
        'mess': mess,
        'username': request.user.username,
        'events': events,
        'info': info,

    })

@login_required(login_url='signin')
def profile(request):
    profile_instance = Profile.objects.filter(user=request.user).first()
    user_instance = request.user

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile_instance)
        user_form = UserForm(request.POST, instance=user_instance)
   
        if form.is_valid() and user_form.is_valid():
            # Update profile model fields
            profile_instance = form.save(commit=False)
            profile_instance.user = user_instance
            profile_instance.save()

            # Update user model fields
            user_instance.email = user_form.cleaned_data['email']
            user_instance.first_name = user_form.cleaned_data['first_name']
            user_instance.last_name = user_form.cleaned_data['last_name']
            user_instance.save()

            return redirect('dashboard:profile')
    else:
        initial_data = {
            'username': user_instance.username,
            'email': user_instance.email,
            'first_name': user_instance.first_name,
            'last_name': user_instance.last_name,
            
        }
        form = ProfileForm(instance=profile_instance, initial=initial_data)
        user_form = UserForm(instance=user_instance)


    return render(request, 'dashboard/profile.html', {
        'form': form,
        'profile': profile_instance,
        'user_form': user_form,
        'title': 'Your Profile',
    })

@login_required(login_url='signin')
def delete(request, pk):
    delete = get_object_or_404(Profile.image, pk=pk, user=request.user)

    if request.method == 'POST':
        delete.delete()
        return redirect('dashboard:profile')

    return render(request, 'dashboard/profile.html', {
        'delete': delete,
        'title': 'Confirm Delete',
    })

# def render_profile_image(request):
#     profile = Profile.objects.filter(user=request.user).first()

#     return render(request, 'dashboard/base.html', {
#         'profile': profile,
#     })

@login_required(login_url='signin')
def dashboard(request):
    # items = Item.objects.filter(created_by=request.user).order_by('?')  # To randomize the listing order
    items = Item.objects.filter(created_by=request.user).order_by('-id')

    paginate = Paginator(Item.objects.filter(created_by=request.user).order_by('?'), 6)
    page= request.GET.get('page')
    itemss = paginate.get_page(page)

    return render(request, 'dashboard/dashboard.html', {
        'items': items,
        'itemss': itemss,
        'title': 'Your Uploads',
    })

@login_required(login_url='signin')
def products(request):
    items = Item.objects.all().order_by('-id')  

    paginate = Paginator(items, 9)  
    page = request.GET.get('page')
    itemss = paginate.get_page(page)

    return render(request, 'dashboard/products.html', {
        'items': items,
        'itemss': itemss,
        'title': 'all Uploads',

    })

# @login_required(login_url='signin')
# def info(request, pk):
#     info = Info.objects.filter(user=request.user).order_by('-id')

#     return render(request, 'dashboard/info.html', {
#         'info': info
#         })

@login_required(login_url='signin')
def info(request, pk):
    # Retrieve the specific message based on the pk and user
    message = get_object_or_404(Info, id=pk, user=request.user)

    # Update the status to mark the message as read
    message.status = True
    message.save()

    return render(request, 'dashboard/info.html', {
        'message': message,
        'title': 'Message',

    })

@login_required(login_url='signin')
def allinfo(request):
    allinfo = Info.objects.filter(user=request.user).order_by('id')

    return render(request, 'dashboard/allinfo.html', {
        'allinfo': allinfo,
        'title': 'All Messages',

        })

dashboard/templates/dashboard/allinfo.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block title %}Messages{% endblock %}

{% block content %}

<style>
    
</style>
<div class="section-header">
    <span>{{title}}</span>
    <h2>{{title}}</h2>
</div>

<ul class="list-group">
{% if allinfo %}
    {% for allinfo in allinfo %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <div class="{% if allinfo.status == False %}bg-secondary bg-opacity-25 p-2 rounded{% endif %} container">
            <a class="dropdown-item rounded-2" href="{% url 'dashboard:single_message' pk=allinfo.pk %}">
            <h2>{{ allinfo.title }}</h2>
            <p style=" width: 100%; overflow-x: hidden;">{{ allinfo.content }}</p>
            <small class="m-auto">{{ allinfo.date }}</small>
            </a>
        <div><hr class="dropdown-divider"></div>
        </div>
    {% endfor %}
    </li>
{% else %}
<p> You have no message.</p>
{% endif %}
</ul>
<a class="btn bg-danger bg-opacity-75 m-3" href="{% url 'dashboard:index' %}">Back</a>







{% endblock %}

dashboard/templates/dashboard/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    <title>Dashboard | {% block title %} {% endblock %}</title>
    <meta content="" name="description" />
    <meta content="" name="keywords" />

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon" />
    <link
      href="{% static 'img/apple-touch-icon.png' %}"
      rel="apple-touch-icon"
    />

    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->

    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet" />
    <link
      href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'vendor/fontawesome-free/css/all.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'vendor/glightbox/css/glightbox.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'vendor/swiper/swiper-bundle.min.css' %}"
      rel="stylesheet"
    />

    <!-- MDB -->
    {% comment %}
    <link rel="stylesheet" href="{% static 'vendor/md/css/mdb.min.css' %}" />
    {% endcomment %}

    <!-- Template Main CSS File -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <style>
      /* Scroll Bar */

      ::-webkit-scrollbar {
        width: 10px;
      }

      ::-webkit-scrollbar-track {
        background: white;
      }

      ::-webkit-scrollbar-thumb {
        background: rgb(90, 89, 89);
        border-radius: 10px;
      }

      ::-webkit-scrollbar-thumb:hover {
        background: rgb(136, 135, 135);
      }
      body {
        background-color: #f8f8f8;
      }
      nav {
        background-color: transparent;
        margin-top: 10px;
      }
      .siddd {
        background-color: rgba(53, 52, 52, 0.795);
        margin-left: -100px;
        margin-top: 10px;
        margin-right: 10px;
        margin-bottom: 10px;
        border-radius: 10px;
        transition: 0.3s ease-in-out;
      }
      .bi-list-nested,
      .bi-list {
        cursor: pointer;
        font-size: larger;
      }
      .bi-list-nested {
        display: none;
      }
      .iconss {
        font-size: 30px;
        background-color: rgb(69, 69, 228);
        border-radius: 20px 8px 8px 8px;
      }
      
      .msgsx {
        position: absolute;
        right: 5px;
        cursor: pointer;
      }
    </style>
  </head>

  <body>
    <!-- ======= Header ======= -->

    <nav class="navbar">
      <div class="container-fluid">
        <div
          class="d-flex"
          style="align-items: center; justify-content: center"
        >
          <a href="{% url 'core:index' %}" class="navbar-brand"
            ><h3>Brand Nova</h3></a
          >
          <i class="bi bi-list"></i>
          <i class="bi bi-list-nested"></i>
        </div>

        <div class="d-flex">
          
          <!-- End Messages Nav -->
          <form class="d-flex" role="search">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>

    <main style="display: flex; flex-direction: row">
      <div class="sidebar d-flex">
        <div
          class="d-flex flex-column flex-shrink-0 siddd"
          style="width: 4.5rem"
        >
          <a
            href="{% url 'core:index' %}"
            class="d-block p-3 link-body-emphasis text-decoration-none"
            title="Home"
            data-bs-toggle="tooltip"
            data-bs-placement="right"
          >
            <img
              src="/static/img/BN.png"
              alt="mdo"
              width="30"
              height="30"
              class="rounded-circle"
            />
            <span class="visually-hidden">Home</span>
          </a>
          <ul class="nav nav-pills nav-flush flex-column mb-auto text-center">
            <li class="nav-item">
              <a
                href="{% url 'dashboard:index' %}"
                class="nav-link py-3 border-bottom rounded-0"
                title="Home"
                data-bs-toggle="tooltip"
                data-bs-placement="right"
              >
                <i class="bi bi-house-door me-2"></i>
              </a>
            </li>
            <li>
              <a
                href="{% url 'dashboard:dashboard' %}"
                class="nav-link py-3 border-bottom rounded-0"
                title="Dashboard"
                data-bs-toggle="tooltip"
                data-bs-placement="right"
              >
                <i class="bi bi-columns-gap me-2"></i>
              </a>
            </li>
            <li>
              <a
                href="#"
                class="nav-link py-3 border-bottom rounded-0"
                title="Products"
                data-bs-toggle="tooltip"
                data-bs-placement="right"
              >
                <i class="bi bi-window-split me-2"></i>
              </a>
            </li>
            <li>
              <a
                href="{% url 'dashboard:products' %}"
                class="nav-link py-3 border-bottom rounded-0"
                title="Posts"
                data-bs-toggle="tooltip"
                data-bs-placement="right"
              >
                <i class="bi bi-microsoft me-2"></i>
              </a>
            </li>
            <li>
              <a
                href="{% url 'dashboard:profile' %}"
                class="nav-link py-3 border-bottom rounded-0"
                title="Profile"
                data-bs-toggle="tooltip"
                data-bs-placement="right"
              >
                <i class="fa-regular fa-user"></i>
              </a>
            </li>
          </ul>
          <div class="dropdown border-top">
            <a
              href="#"
              class="d-flex align-items-center justify-content-center p-3 link-body-emphasis text-decoration-none dropdown-toggle"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              <img
                src="{{ profile.image.url }}"
                alt="img"
                width="24"
                height="24"
                class="rounded-circle"
              />
            </a>
            <ul class="dropdown-menu text-small shadow">
              <li>
                <a class="dropdown-item" href="{% url 'items:new' %}"
                  >New Post</a
                >
              </li>
              <li><hr class="dropdown-divider" /></li>
              <li>
                <form action="{% url 'core:logout' %}" method="post">
                  {% csrf_token %}
                  <button class="dropdown-item" type="submit">Logout</button>
                </form>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="content d-flex" style="width: 100%">
        <div class="container">{% block content %} {% endblock %}</div>
      </div>
    </main>
    <!-- End Header -->
    <!-- Start Page  -->

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-5 col-md-12 footer-info">
            <a
              href="{% url 'core:index' %}"
              class="logo d-flex align-items-center"
            >
              <span>BRAND NOVA</span>
            </a>
            <p class="text-center">
              Welcome to Brand Nova, your ultimate destination for all things web. We specialize in delivering innovative web design templates, engaging tutorials, and a dynamic online community platform.
            </p>
          </div>
        </div>
      </div>

      <div class="container mt-4">
        <div class="copyright">
          &copy; Copyright <strong><span>BRAND NOVA</span></strong
          >. All Rights Reserved
        </div>
      </div>
    </footer>
    <!-- End Footer -->
    <!-- End Footer -->

    <a
      href="#"
      class="scroll-top d-flex align-items-center justify-content-center"
      ><i class="bi bi-arrow-up-short"></i
    ></a>

    <div id="preloader"></div>

    <!-- End Page  -->

    <!-- Vendor JS Files -->
    <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'vendor/aos/aos.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>

    <!-- MDB -->
    {% comment %}
    <script
      type="text/javascript"
      src="{% static 'vendor/md/js/mdb.min.js' %}"
    ></script>
    {% endcomment %}

    <!-- Template Main JS File -->
    <script src="{% static 'js/main.js' %}"></script>

    <!-- Chart Js -->
    <script src="{% static 'js/chart.js' %}"></script>

    <!-- J Queery -->
    <script src="{% static 'js\jquery-3.7.1.min.js' %}"></script>

    <script>
      $(document).ready(function () {
        $(".nav-link").click(function () {
          $(this).toggleClass("active");
        });
      
        $(".bi-list").click(function () {
          $(this).hide();
          $(".bi-list-nested").css("display", "block");
          $(".siddd").css("margin-left", "10px");
        });
      
        $(".bi-list-nested").click(function () {
          $(this).hide();
          $(".bi-list").css("display", "block");
          $(".siddd").css("margin-left", "-100px");
        });
      
        // messages dropdown
      
        $(".msgsi").click(function () {
          $(".msgs").toggleClass("d-none");
        });
      
        $(".msgsx").click(function () {
          $(".msgs").hide();
        });
      });
      
    </script>
  </body>
</html>

dashboard/templates/dashboard/dashboard.html
{% extends 'dashboard/base.html' %}
{% load static %}


{% block title %}{{ title }}{% endblock %}

{% block content %}

<div class="section-header">
    <span>{{title}}</span>
    <h2>{{title}}</h2>
</div>

<div class="row gy-4 p-5">
          
    {% if itemss %}
      {% for item in itemss %}

          <div class="col-lg-4 col-md-6 " data-aos="fade-up" data-aos-delay="100">
              <div class="card rounded" style="border-radius: 15px;box-shadow: 0 1px 3px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
              ">
                <div class="card-img">
                  <img src="{{ item.image.url }}" alt="" class="img-fluid">
                </div>
                <h3><a href="{% url 'items:detail' item.id %}" class="stretched-link p-3 text-center">{{ item.name }}</a></h3>
                <p class="p-3">{{ item.description }}</p>
              </div>
          </div>

      {% endfor %}
    {% else %}
          <h2 class="text-center">You Have Made No Uploads, Click <a class="" href="{% url 'items:new' %}">Here</a> To Create A Post.</h2>
    {% endif %}
    <!-- End Service Item -->
    <div class="d-flex" style="flex-direction: column;">
    
      {% if itemss %}
      <button type="button" class="btn btn-primary my-1">
        Number of Pages <span class="badge text-bg-success bg-opacity-75">{{ itemss.paginator.num_pages }}</span>
      </button>
      <br>
      <button type="button" class="btn btn-primary">
        Number of Posts <span class="badge text-bg-success bg-opacity-75">{{ items|length }}</span>
      </button>
      {% else %}
      <button type="button" class="btn btn-primary">
        Number of Posts <span class="badge text-bg-success bg-opacity-75">{{ items|length }}</span>
      </button>
      <br>
      {% endif %}
      <br>
      <hr>
      <br/>
    </div>

    {% if itemss %}

    <div class="justify-content-center">
      <nav aria-label="Page navigation example">
        <ul class="pagination">
        {% if itemss.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ itemss.previous_page_number }}">Prev</a></li>
        {% endif %}
  
          <li class="page-item"><a class="page-link" href="#">Page {{ itemss.number }}</a></li>
        {% if itemss.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ itemss.next_page_number }}">Next</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ itemss.paginator.num_pages }}">Last &raquo</a></li>
        {% endif %}
        </ul>
      </nav>
    </div>

    {% else %}

    {% endif %}


</div>

{% endblock %}

dashboard/templates/dashboard/info.html
{% extends 'dashboard/base.html' %}
{% load static %}


{% block title %}Messages{% endblock %}

{% block content %}
<div class="section-header">
    <span>{{title}}</span>
    <h2>{{title}}</h2>
</div>




<ul class="list-group">
    <li class="list-group-item justify-content-between align-items-center">
        <h2><u>{{ message.title }}</u></h2>
        <p>{{ message.content }}</p>
        <small>{{ message.date }}</small><br>
    </li>
</ul>
<a class="btn bg-secondary bg-opacity-75 m-3" href="{% url 'dashboard:index' %}">Dashboard</a>
<a class="btn bg-primary bg-opacity-75 m-3" href="{% url 'dashboard:allinfo' %}">All Messages</a>


{% endblock %}

dashboard/templates/dashboard/products.html
{% extends 'dashboard/base.html' %}
{% load static %}


{% block title %}{{ title }}{% endblock %}

{% block content %}

<div class="section-header">
    <span>{{title}}</span>
    <h2>{{title}}</h2>
</div>
<div class="row gy-4 p-5">
          
    {% if itemss %}
      {% for item in itemss %}

          <div class="col-lg-4 col-md-6 " data-aos="fade-up" data-aos-delay="100">
              <div class="card rounded" style="border-radius: 15px;box-shadow: 0 1px 3px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
              ">
                <div class="card-img">
                  <img src="{{ item.image.url }}" alt="" class="img-fluid">
                </div>
                <h3><a href="{% url 'items:detail' item.id %}" class="stretched-link p-3 text-center">{{ item.name }}</a></h3>
                <p class="p-3">{{ item.description }}</p>
              </div>
          </div>

      {% endfor %}
    {% else %}
          <h2 class="text-center">You Have Made No Uploads, Click <a class="" href="{% url 'items:new' %}">Here</a> To Create A Post.</h2>
    {% endif %}
    <!-- End Service Item -->
    <div class="d-flex" style="flex-direction: column;">
    
      {% if itemss %}
      <button type="button" class="btn btn-primary my-1">
        Number of Pages <span class="badge text-bg-success bg-opacity-75">{{ itemss.paginator.num_pages }}</span>
      </button>
      <br>
      <button type="button" class="btn btn-primary">
        Number of Posts <span class="badge text-bg-success bg-opacity-75">{{ items|length }}</span>
      </button>
      {% else %}
      <button type="button" class="btn btn-primary">
        Number of Posts <span class="badge text-bg-success bg-opacity-75">{{ items|length }}</span>
      </button>
      <br>
      {% endif %}
      <br>
      <hr>
      <br/>
    </div>

    {% if itemss %}

    <div class="justify-content-center">
      <nav aria-label="Page navigation example">
        <ul class="pagination">
        {% if itemss.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ itemss.previous_page_number }}">Prev</a></li>
        {% endif %}
  
          <li class="page-item"><a class="page-link" href="#">Page {{ itemss.number }}</a></li>
        {% if itemss.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ itemss.next_page_number }}">Next</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ itemss.paginator.num_pages }}">Last &raquo</a></li>
        {% endif %}
        </ul>
      </nav>
    </div>

    {% else %}

    {% endif %}


</div>

{% endblock %}